[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  # Imposta qui l'URL del backend FastAPI in produzione (aggiorna dopo il deploy)
  # Esempio: "https://api.miodominio.it"
  VITE_API_BASE = ""

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Reverse-proxy API routes to the backend on Render (replace the URL below with your actual backend URL)
[[redirects]]
  from = "/upload"
  to = "https://app-orario-backend.onrender.com/upload"
  status = 200
  force = true

[[redirects]]
  from = "/run"
  to = "https://app-orario-backend.onrender.com/run"
  status = 200
  force = true

[[redirects]]
  from = "/status/*"
  to = "https://app-orario-backend.onrender.com/status/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/results/*"
  to = "https://app-orario-backend.onrender.com/results/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/download/*"
  to = "https://app-orario-backend.onrender.com/download/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/examples/*"
  to = "https://app-orario-backend.onrender.com/examples/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/logs/*"
  to = "https://app-orario-backend.onrender.com/logs/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/jobs/*"
  to = "https://app-orario-backend.onrender.com/jobs/:splat"
  status = 200
  force = true

# Optional: SPA fallback so deep links route to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
